- src/main/java/com/networknt/schema/PatternValidator.java
- src/test/resources/tests/pattern.json
Closes #6. There is the larger issue that json schema regular expressions need to use ECMA 262 regular expressions instead of Java regular expressions. I can open a separate ticket for that. I think other people are solving it by using the Rhino JS engine for Java 7 or the Nashorn JS engine for Java 8.
> Match subsequence instead of entire input sequence.

- pom.xml
As silly as this may sound, I've still got to compile against Java 7 for Jenkins plugins, at least for a while longer. I'd *really* like to use this library in a key Jenkins plugin, but can't unless it's compiled against Java 7. I tried this locally and everything worked fine. Thanks!
(Oh, and I also bumped the version to 0.1.5-SNAPSHOT)
> Switch to targeting Java 7

- src/main/java/com/networknt/schema/ValidatorTypeCode.java
on ValidatorTypeCode are some MessageFormat with empty formats that cause a empty message on ValidationMessage.
> default messages on empty messages in ValidatorTypeCode

- pom.xml
- src/main/java/com/networknt/schema/OneOfValidator.java
Only few lines in OneOfValidator.java use constructs specific to java 1.7 and 1.8. I rewrote them with older syntax.
Unfortunately, the dependencies of junit tests of this project are compiled for java 1.7, so for the tests to work out of the box in Eclipse I had to mention both versions in maven-compiler-plugin config. Eclipse picks the latest one for the project execution env.
We, personally, use java 1.7 in our project and we need this library.
> Don't leave out 50% of your audience who still use older java

- pom.xml
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/url/ClasspathURLStreamHandler.java
- src/main/java/com/networknt/schema/url/URLFactory.java
The original implementation supports schema's to be accessible either in http, http, file, etc.. This pull request adds the possibility to also refer to schema's present in the applications classpath.
> Replaced 'new URL' with a call to a new URLFactory 

- src/main/java/com/networknt/schema/ValidationMessage.java
Array.equals() does the right thing, here. It compares the shape of each
array, then object equality of the members. Where it would fail is on
a String[][].
> Remove unnecessary todo

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/DependenciesValidator.java
- src/main/java/com/networknt/schema/EnumValidator.java
- src/main/java/com/networknt/schema/FormatValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/MaxItemsValidator.java
- src/main/java/com/networknt/schema/MaxLengthValidator.java
- src/main/java/com/networknt/schema/MaxPropertiesValidator.java
- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinItemsValidator.java
- src/main/java/com/networknt/schema/MinLengthValidator.java
- src/main/java/com/networknt/schema/MinPropertiesValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/main/java/com/networknt/schema/MultipleOfValidator.java
- src/main/java/com/networknt/schema/NotAllowedValidator.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PatternValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/ReadOnlyValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/RequiredValidator.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/main/java/com/networknt/schema/UniqueItemsValidator.java
- src/main/java/com/networknt/schema/ValidationMessage.java
For things that might be read by humans, maintaining order can be
valuable. This change uses LinkedHashSet rather than HashSet to
maintain the iteration order of error in the order they're encountered.
Additionally, there are a few optimzations in validators:
- Using singletonSet and emptySet rather than a *HashSet when
appropriate
- Map iteration optimization
- StringBuilder optimization
> Use LinkedHashSets for ValidationMessages

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
When JsonSchemaFactory.getSchema is called with anything else than a URL, a specified ID property used to lead to the URI being resolved even if it was not necessary (because there was no ref that cannot be satisfied with the current schema). If the validation code is called to verify a Schema before it is accepted as the "official" schema for a given URI, it will fail because the resolved URI either does not exist yet or contains an older version.  Thus I changed the implementation to resolve the sub schema node lazily.
> Resolve sub schema node only if really needed

- src/main/java/com/networknt/schema/JsonSchemaException.java
- src/main/java/com/networknt/schema/RefValidator.java
Documents were validated even if "$ref" pointed to a non-existing schema. 
The json schema spec does not explicitely  state how to treat this case, but I would like to argue that a non-existing referenced schema should be treated as an error.
> References that cannot be resolved should be treated as an error

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
An often-used pattern in conjunction with oneOf is to use a single value
enum as a constant where each oneOf alternative typically has a different
constant.
If the corresponding property is set in the json node (and thus is
textual) we can skip all alternatives that have a different constant
value defined for that property since they will definitely not match.
For schemas with many alternatives and a lot of items that need to run
through those alternatives, I found this to speedup validation
considerably (30% faster in my case).
Please note that this commit contains the semantics from PR "unresolved-refs-are-errors" as well - if you object to that one, I can adjust this PR.
> Optimization for OneOf

- src/main/java/com/networknt/schema/EnumValidator.java
There's two performance optimizations in this:
* Making `nodes` a `HashSet` means lookups will be in O(1) time.
* Building `error` with a `StringBuilder` and not concatenations makes it run in O(n) time.
> EnumValidator optimizations

- src/main/java/com/networknt/schema/PatternValidator.java
Currently, `pattern` is applied to strings, numbers, and integers. According to the [spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.3),
> A string instance is considered valid if the regular expression matches the instance successfully. 
I think that means patterns are ignored for non-strings.
> Only apply pattern validation on strings

- src/main/java/com/networknt/schema/RequiredValidator.java
- src/test/resources/tests/required.json
The spec for `require` say
>  An object instance is valid against this keyword if every item in the array is the name of a property in the instance.
`require` shouldn't be applied to non-objects.
> Only apply required validator to objects

- src/main/java/com/networknt/schema/JsonSchema.java
To improve extensibility by library users, it would be very helpful if one can use the full JsonSchema constructor and thus create a JsonSchema for a part of a schema and explicitely validate only that part.
> Make remaining JsonSchema constructors public

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/resources/tests/oneOf.json
There was actually a bug in my previous commit for shortcut validation of oneOf - we reported success even if none of the schemas validated.  Sorry for sending you a patch without appropriate test case.
Here is the test case and a fix for that one.
But I noticed that https://github.com/networknt/json-schema-validator/commit/a77673858c7df3f2b08eedb6b971cd74fda58920#comments seems to have originally introduced the behaviour I called "bug" above deliberately. Unfortunately the question posted by @bamateus underneath that commit was not answered. As far as I understand the json schema spec, we must not validate oneOfs when none of the schemas validates. And if the validation error is about an additional property, it still is a validation error (if it was reported wrongly then it should be …
> One of was broken - it did not fail when there were no valid schemas

- src/main/java/com/networknt/schema/EnumValidator.java
- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/resources/tests/enum.json
- src/test/resources/tests/maximum.json
- src/test/resources/tests/minimum.json
@NicholasAzar @stevehu Since the RequestValidator is built on json-schema-validator. There is another PR related to this issue can be found in networknt/light-rest-4j repo. These changes in different repo contributions to the same issue.
RFC which specifies the details of fix can be found here: https://github.com/networknt/light-rfcs/blob/master/light-rest-4j/0001-openapi-validator-bug-fix.md
> Fixed validation for path parameters and query parameters

- src/main/java/com/networknt/schema/TypeValidator.java
- src/test/java/com/networknt/schema/TypeValidatorTest.java
Fixes #118 , yet leaves `+1` as a valid option
> Almost JSON-spec compliant validation of numeric values

- src/main/java/com/networknt/schema/MultipleOfValidator.java
- src/test/resources/tests/multipleOf.json
Related issue: https://github.com/networknt/json-schema-validator/pull/139
Since the division and multiple of double type do not have the enough accuracy. Convert dividend and divisor into BigDecimal to do the validation would be more reliable.
> Fix multipleOf validator 

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/test/java/com/networknt/schema/UrlMappingTest.java
- src/test/resources/tests/url_mapping/schema-with-ref-mapping.json
- src/test/resources/tests/url_mapping/schema-with-ref.json
With this change, I think that anywhere a URL is used in a schema, it can be mapped to a local or alternate URL to be retrieved from.
Fixes #134
> feat: Use URL mappings for $ref and other URLs

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/java/com/networknt/schema/UrlMappingTest.java
See https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#dm-maps-and-sets-of-urls-can-be-performance-hogs-dmi-collection-of-urls
Fixes #136 by introducing breaking change to the URL mapping feature of versions 1.0.5 thru 1.0.7
> fix: avoid performance penalty of using URL in map or set

- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/test/java/com/networknt/schema/MaximumValidatorTest.java
- src/test/java/com/networknt/schema/MinimumValidatorTest.java
related issue: https://github.com/networknt/json-schema-validator/issues/147
-fixed when the node is BigInteger, when it's smaller than Long.MAX_VALUE, it should do the comparison instead of return false directly.
-added test cases.
> fixed for PR https://github.com/networknt/json-schema-validator/pull/148

- src/test/java/com/networknt/schema/ThresholdMixinPerfTest.java
While there is a wide range of tradeoffs between code readability/maintainability and performance it would be interesting to look at how much speed is given up with different levels of readability.
This PR offers a simple test-case-like setup that allows do have some ball-park numbers to make discussion more concrete. Also by no means is this test suite complete or precise.
Since there was no isolated environment to do the benchmarking on, I opted for benchmarking with respect to some "base" cases. Base cases were chosen as comparing two `DoubleNode` and comparing two `LongNode`. 
Time is measured as difference between start and end of `ThresholdMixin` execution, and averaged over number of executions. Then average time for a particular case is compared to average time of a corresponding …
> Insights into performance gains of tuning min/max validators

- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/test/java/com/networknt/schema/MaximumValidatorPerfTest.java
- src/test/java/com/networknt/schema/MaximumValidatorTest.java
- src/test/java/com/networknt/schema/MinimumValidatorTest.java
Proposed solution to issue raised in #171
Organized tests into sections (positive and negative) tests for `number`, `integer`, and `integer` with exclusive type of behavior.
Each collection of inputs is augmented with it's corresponding quoted counter part. 
Quoting thresholds does not seem necessary as they can be parsed into numbers at schema creation time.
> fixes #171 validation of quoted numerics added

- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/resources/tests/anyOf.json
Fixes issue #173
Also added a way to validate the error count in test cases using the optional int field `"errorCount"`
> #173 - Do not ignore other errors in case of anyOf validator

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
This just has to do with a minor limitation that I've encountered. 
The JsonSchemaFactory allows URIFactories to be given for various URI schemes. The JsonSchemaFactory then builds up a URISchemeFactory that delegates creation to URIFactories based on the needed scheme. This was something that I previously added in to allow custom URI support and all that good stuff. 
The problem is that the users of this library will also need to create URIs. The JsonSchemaFactory accepts URIs for the location of the schema to use. So the user essentially needs to have their own URI creation utility and then we'll also use a separate one under the hood. This doesn't work out very well, because the user won't be able to use our custom classpath URI factory/fetcher.
If we simply just provide access to the …
> Expose URI Factory

- src/main/java/com/networknt/schema/JsonSchemaRef.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/ValidationContext.java
Prevents recursive parsing of json schema when conditions like told in json-schema specification, point 8.3.1:
https://json-schema.org/latest/json-schema-core.html#rfc.section.8.3.1
"A schema MUST NOT be run into an infinite loop against a schema. For example, if two schemas "#alice" and "#bob" both have an "allOf" property that refers to the other, a naive validator might get stuck in an infinite recursive loop trying to validate the instance. Schemas SHOULD NOT make use of infinite recursive nesting like this; the behavior is undefined. "
> Fix issue #180: Prevents recursive parsing of $ref references.

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/resources/tests/oneOf.json
This pull request is for issue #177.
First, I've added a commit that reproduces the problem. In essence, after encountering a schema failure, the remaining schemata in the OneOf array aren't being checked. I'm not entirely sure of the purpose of the code that I'm removing with this commit.
> Fix/#177 One Of Bug

- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/resources/tests/if.json
This feature is very useful for our project.
The implementation of theses keywords was guided by [SPEC Draft 7](https://json-schema.org/understanding-json-schema/reference/conditionals.html).
> IF-THEN-ELSE Conditional (Draft 7)

- src/main/java/com/networknt/schema/RefValidator.java
- src/test/resources/tests/ref.json
- src/test/resources/tests/subSchemas.json
Avoid java.lang.StackOverFlowError.
related issue https://github.com/networknt/json-schema-validator/issues/208
> Fixing ref validation with same name but different files

- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/test/resources/draft2019-09/oneOf.json
- src/test/resources/draft4/oneOf.json
- src/test/resources/draft6/oneOf.json
- src/test/resources/draft7/oneOf.json
The schema
```
"oneOf": [
{
"properties": {
"bar": {"type": "integer"},
"baz": {"type": "integer"}
},
"required": ["bar"]
},
{
"properties": {
"foo": {"type": "string"}
},
"required": ["foo"]
}
]
```
fails to match the instance 
```
{"bar": 2}
```
because `PropertiesValidator` exits the first oneOf branch when "baz" is not matched, even though it is not required. This PR fixes this.
> Fix for oneOf when not all properties are matched

- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/java/com/networknt/schema/V201909JsonSchemaTest.java
- src/test/java/com/networknt/schema/V6JsonSchemaTest.java
- src/test/java/com/networknt/schema/V7JsonSchemaTest.java
- src/test/resources/draft2019-09/refRemote.json
- src/test/resources/draft2019-09/refRemote_ignored.json
- src/test/resources/draft6/refRemote.json
- src/test/resources/draft6/refRemote_ignored.json
- src/test/resources/draft7/refRemote.json
- src/test/resources/draft7/refRemote_ignored.json
Schema id has not been resolved correctly for v6 and up as there's different id field name.
Not sure if you require to create a new issue for every pull request, seems like the problem is known (there were ignored test cases), but I haven't found any issue related to this.
> Resolve schema id from the schema document (for v6 and above)

- src/test/java/com/networknt/schema/UnknownMetaSchemaTest.java
Even a very simple code cannot run in my computer.
My environment is:
- Mac 10.15.4
- java version "1.8.0_241"
The trace log is :
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=58197:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirt …
```
> unknownMetaSchema error reproduce

- src/main/java/com/networknt/schema/PatternValidator.java
This is necessary to guarantee that classes from org.joni and org.jcodings are only loaded when the ecma262 configuration is set. Having both in the same class and one of the class' members being a class from the before mentioned packages fails with a NoClassDefFoundException when running in an OSGI environments with the imports of the packages being optional and not present. (fixes #307 )
> Split the PatternValidator into 2 classes.

- src/main/java/com/networknt/schema/JsonMetaSchema.java
There was potentially race condition that could lead to situation in which we could get multiple log entries regarding the same keyword being unknown. Such case was when more than one thread was doing check on `containsKey` before they went into `put`.
Simple fix for this is to always add element to the `UNKNOWN_KEYWORDS` map and than check if it was present. See [documentation for `put` method and what value it returns](https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentHashMap.html#put(K,%20V)). Doing this that way shouldn't impact performance.
> FIX: potential duplicate log entry due to race condition

- pom.xml
This PR makes `json-schema-validator` work better with JDK9+ w.r.t. modularization and a couple build fixes for JDK11+:
* `commons-lang` is bumped from `3.5` to `3.7` so the generated `module-info` can point to a fixed module name (instead of using an "automatic module name" determined from the JAR's filename, which is a discouraged practice).  `slf4j-api` was not bumped because the next version with any module support is `2.0.0-alpha1`, which I figured was too drastic of a version bump.
* `moditect-maven-plugin` is added to build a `module-info.class` class file which serves as the module descriptor.  This works even during a JDK8 build because `moditect-maven-plugin` will generate the `.class` file itself and place it under `META-INF/versions/9`, making this a [multi-release …
> Generate module-info, fix build on JDK11+

- src/main/java/com/networknt/schema/JsonMetaSchema.java
I am not sure I am able to  test this change. I did not find out any idea how to do it 😄 
You can find the reference to the schema here:
https://json-schema.org/understanding-json-schema/reference/generic.html#comments
and here:
https://json-schema.org/draft-07/json-schema-core.html#rfc.section.9
> Add '$comment' as a NonValidationKeyword for v7 and v2019 drafts

- src/main/java/com/networknt/schema/JsonMetaSchema.java
`contentMediaType`, `contentEncoding` and `examples` should be treated as keywords according to the spec
https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.8.6 and https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.5
> Add contentMediaType, contentEncoding and examples as a NonValidationKeyword

- src/main/java/com/networknt/schema/DateTimeValidator.java
- src/main/java/com/networknt/schema/EnumValidator.java
- src/main/java/com/networknt/schema/ExclusiveMaximumValidator.java
- src/main/java/com/networknt/schema/ExclusiveMinimumValidator.java
- src/main/java/com/networknt/schema/FormatValidator.java
- src/main/java/com/networknt/schema/MaxLengthValidator.java
- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinLengthValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/main/java/com/networknt/schema/PatternValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/TypeFactory.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/main/java/com/networknt/schema/UUIDValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/main/java/com/networknt/schema/format/EmailValidator.java
- src/test/java/com/networknt/schema/TypeFactoryTest.java
This PR tries to address #334 . The solution is not perfect, however, it improves the current situation.
In my opinion, we should not merge this PR as is. We should wait jackson-databind's upcoming `2.12.0` release which will [introduce](https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION-2.x#L26-L28) `JsonNode.canConvertToExactIntegral()`, a new method that will meet our purpose.
I wanted to open the PR so that maintainers can see my approach, the way I provide config to all validators etc.
Once jackson-databind 2.12.0 is out, I'll replace my solution with a call to `canConvertToExactIntegral`
> Improve type validation of numeric values

- doc/config.md
Hi @stevehu , I didn't create a dedicated issue for the commit. Please let me know if I should do so or if I can improve the docs update.
> Update docs about javaSemantics flag

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
This lets me do something like this:
```java
JsonSchemaFactory factory = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7))
.uriFetcher(new JenkinsWorkspaceFileFetcher(), JenkinsWorkspaceFileFetcher.SUPPORTED_SCHEMES)
```
`JenkinsWorkspaceFileFetcher.SUPPORTED_SCHEMES` is a `Set<String>`, which can't be passed into varargs. But varargs can be passed into an `Iterable<String>` if you wrap it with `Arrays.asList(varargs)`, and it is cheap too since an `ArrayList<>` is just backed by an array.
> Add builder method that accepts iterable

- src/main/java/com/networknt/schema/JsonMetaSchema.java
Following #328 and #341 , also `$anchor` and `deprecated` were introduced as keywords in draft `2019-09`.
See: 
- https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.3
- https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3
> Add 'anchor' and 'deprecated' as NonValidationKeywords for v2019-09 draft

- doc/yaml-line-numbers.md
Example describing how to retain YAML source file location information in processed and validated JSON tree
Fixes #340
> YAML source location handling (#340)

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/resources/draft6/oneOf.json
OneOf validator is not throwing valid error if any of the child nodes has invalid schemas.
Proposed Fix: If there is no valid schema in child nodes, then clear existing error list which got generated while validating child nodes and push OneOf validation to the error list as per "OneOf" attribute requirement.
Since, "OneOf" validator, in every scenario, validates and generates the error list while validating the child nodes. The error list has to be cleared, in order, to push OneOf validation to the error list as per "OneOf" attribute requirement.
Once the "OneOf" scenario is not detected after counting the valid schemas i.e. 'if (numberOfValidSchema != 1)', then OneOf validation error is pushed to the error list as per "OneOf" attribute requirement.
> #354-fixed OneOf validation error if number of valid schemas is not equal to 1

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/java/com/networknt/schema/Issue295Test.java
- src/test/resources/data/issue295.json
- src/test/resources/schema/issue295-v7.json
Issue #295 appears to be caused when the validation of one element of a oneOf schema fails due to a failed 'required' block (setting ValidatorState.matchedNode to false), and a later schema succeeds without matching any 'properties' block (which would set ValidatorState.matchedNode to true).
I'm not familiar enough with the entire code to be sure that my fix is correct, but it fixes the reported testcase and I see no immediate problems.
> Validation of oneOf depends on schema order

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/DependenciesValidator.java
- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
Updated `JsonSchema` to lazy load the validators instead of using the `initialize()` function in order to fix parallel processing (https://github.com/networknt/json-schema-validator/issues/335).
This change still works with the `CyclicDependencyTest` added for https://github.com/networknt/json-schema-validator/issues/258.
> Fixed parallel processing (issue-335)

- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/TypeFactory.java
- src/test/java/com/networknt/schema/TypeFactoryTest.java
Should (partially) address #344
The idea is that this allows allows for simpler Narrowing of types when it's safe (from round doubles to integers) since this conversion doesn't lose information.
> Add lossless narrowing convertion

- doc/validators.md
- src/main/java/com/networknt/schema/FormatKeyword.java
- src/test/java/com/networknt/schema/OverrideValidatorTest.java
This pull request is overwrite the EmailValidator if I set custom email format.
The EmailValidator applied in "format: email" doesn't meet the requirements of my project, and I would like to overwrite it.
But, constructor of JsonSchema is private, and inner class Builder is forced to use EmailValidator in the case of "format: email" in the build method.
> override default EmailValidator, if set custom email format

- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/java/com/networknt/schema/OpenAPI30JsonSchemaTest.java
- src/test/resources/openapi3/discriminator.json
Attempt to implement #35 for `anyOf` and `allOf`
> Add discriminator support for #35

- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/resources/openapi3/discriminator.json
Also fixes the special situation of nested discriminators not working correctly when the parent schema has a discriminator, but is not referenced via anyOf/$ref
> Fix for #398. 

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/test/java/com/networknt/schema/Issue314Test.java
- src/test/java/com/networknt/schema/UnknownMetaSchemaTest.java
- src/test/resources/schema/issue314-v7.json
In https://github.com/networknt/json-schema-validator/commit/e32a5410a73efb9ce7f50307cf000e28f0902f84, schema normalization was introduced to fix https://github.com/networknt/json-schema-validator/issues/273 however it assumes the given schema is available over HTTPS.
https://github.com/networknt/json-schema-validator/blob/e32a5410a73efb9ce7f50307cf000e28f0902f84/src/main/java/com/networknt/schema/JsonSchemaFactory.java#L406
As reported in https://github.com/networknt/json-schema-validator/issues/314, some schemas are not available over HTTPS. For example, https://iglucentral.com (it just hangs with https), see https://github.com/snowplow/iglu-central/issues/1067.
Therefore https://github.com/networknt/json-schema-validator/issues/314 blocks …
> Introduce `forceHttps` flag in `JsonSchemaFactory.Builder`

- src/main/java/com/networknt/schema/JsonSchema.java
- src/test/java/com/networknt/schema/Issue406Test.java
Fixes https://github.com/networknt/json-schema-validator/issues/416 my marking each JsonSchema as being initialized
> Fix for StackOverFlowErrors occurring in case of circular $ref validators

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
additionalPropertiesSchema can be null by some code paths, but preloadJsonSchema assumes it's always non-null.
> Avoid NPE in AdditionalPropertiesValidator

- src/main/java/com/networknt/schema/JsonMetaSchema.java
Issue:
When using vertx, there is a keyword `exampleSetFlag` present in swagger which is transitive dependency of vertx . So when we run the verticle we get a warning like this :- 
`<onMetaSchema:338> [oop-thread-1]  Unknown keyword exampleSetFlag - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword`
PR purpose :- 
It adds the variable `exampleSetFlag` to the nonValidationKeyword in V4 since the OpenApiv3 use the Json schema v4 --> `    private static final JsonMetaSchema META_SCHEMA = JsonMetaSchema.builder(JsonMetaSchema.getV4().getUri(), JsonMetaSchema.getV4()).addKeyword(new NonValidationKeyword("example")).build();`
> Added exampleSetFlag to nonValidationKeyword

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonValidator.java
- src/main/java/com/networknt/schema/NonValidationKeyword.java
- src/main/java/com/networknt/schema/PatternValidator.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
- src/test/java/com/networknt/schema/CustomMetaSchemaTest.java
- src/test/java/com/networknt/schema/JsonWalkTest.java
`JsonValidator#preloadJsonSchema` is not required so there is no point in forcing it to be implemented in each validator. 
I came across the fact that I need to implement this method in my custom validator. It looks like this is not required, so let's mark it as the default value.
> JsonValidator: mark `preloadJsonSchema` as default

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/test/java/com/networknt/schema/JsonMetaSchemaTest.java
PR changes regex pattern for time to "^\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?$"
> issue-478 : Time format validation supports milliseconds

- doc/specversion.md
Makes the whole document significantly more readable IMHO
> Add Java Syntax Highlighting to specversion.md

- pom.xml
- src/main/java/com/networknt/schema/IfValidator.java
- src/test/java/com/networknt/schema/Issue366FailFast.java
- src/test/java/com/networknt/schema/Issue366FailFastTest.java
- src/test/java/com/networknt/schema/Issue366FailSlowTest.java
- src/test/java/com/networknt/schema/Issue386Test.java
- src/test/resources/data/issue386.json
- src/test/resources/draft2019-09/if-then-else.json
- src/test/resources/draft7/if-then-else.json
- src/test/resources/schema/issue386-v7.json
Fix for https://github.com/networknt/json-schema-validator/issues/386
When failFast is enabled the code that builds the ValidationMessages throws an exception rather than returning a Set.
In if/else/then blocks this could cause the validation to fail whenever an 'if' was false.
I've a basic change here to just wrap the if validation in a try/catch if that's appropriate?
Btw, when running the tests I found that Issue366Test wasn't working, as it was looking in the wrong location (but otherwise is not related to this change)
> Issue386: FailFast should not cause exception on if

- doc/walkers.md
- pom.xml
- src/main/java/com/networknt/schema/ApplyDefaultsStrategy.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/java/com/networknt/schema/JsonWalkApplyDefaultsTest.java
- src/test/resources/data/walk-data-default.json
- src/test/resources/schema/walk-schema-default.json
At https://json-schema.org/understanding-json-schema/reference/generic.html they say of the default keyword
> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.
So before this PR, the 'default' keyword is ignored during both validation and walking.  But this PR allow the user to apply defaults during walking. …
> apply default in objects and arrays

- src/test/java/com/networknt/schema/BaseSuiteJsonSchemaTest.java
- src/test/java/com/networknt/schema/Issue425Test.java
- src/test/java/com/networknt/schema/Issue428Test.java
- src/test/java/com/networknt/schema/OpenAPI30JsonSchemaTest.java
Hi,
This PR fixes 4 violations of [Sonar Rule 2142: '"InterruptedException" should not be ignored'](https://rules.sonarsource.com/java/RSPEC-2142). This is done without introducing any new violations of Sonar rules.
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2142](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#interruptedexception-should-not-be-ignored-sonar-rule-2142).
P.S.: Note that this PR is not created/submitted by a bot. If you have any feedback, please leave them as comments.
> Fix violations of Sonar rule 2142

- src/test/java/com/networknt/schema/CollectorContextTest.java
`testCollectorContextWithKeyword` was failing under [NonDex](https://github.com/TestingResearchIllinois/NonDex) due to implementation-defined ordering of the list of context values.  This PR fixes that flakiness by sorting the list in natural order before inspecting it.
> Fix flakiness in `CollectorContextTest`

- src/main/java/com/networknt/schema/uri/ClasspathURLStreamHandler.java
This fixes the errors when trying to load classpath references, like:
Caused by: java.lang.NullPointerException
at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getResourceAsStream(ClasspathURLStreamHandler.java:83) ~[amcrm-1.0-SNAPSHOT.jar:?]
at com.networknt.schema.uri.ClasspathURLStreamHandler$ClassPathURLConnection.getInputStream(ClasspathURLStreamHandler.java:69) ~[amcrm-1.0-SNAPSHOT.jar:?]
at java.net.URL.openStream(URL.java:1165) ~[?:?]
at com.networknt.schema.uri.ClasspathURLFetcher.fetch(ClasspathURLFetcher.java:39) ~[amcrm-1.0-SNAPSHOT.jar:?]
at com.networknt.schema.uri.URISchemeFetcher.fetch(URISchemeFetcher.java:50) ~[amcrm-1.0-SNAPSHOT.jar:?]
at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:351) ~[amcrm-1.0-SNAPSHOT.jar:?] …
> Handle the situation when context class loader is null

- src/main/java/com/networknt/schema/ItemsValidator.java
- src/test/java/com/networknt/schema/Issue493Test.java
- src/test/resources/data/issue493-invalid-1.json
- src/test/resources/data/issue493-invalid-2.json
- src/test/resources/data/issue493-valid-1.json
- src/test/resources/data/issue493-valid-2.json
- src/test/resources/schema/issue493.json
From Issue #493 , the root cause is that the 'parent schema' of an additionalItems was always be 'null'. So that when looking for the $ref, only those inside 'additionalItems' can be got successfully.
Please let me know if the code I change makes sense and doesn't cause any side effects.
> parent schema of additionItems can be correctly referenced (#493)

- CHANGELOG.md
- doc/config.md
- src/main/java/com/networknt/schema/TypeFactory.java
- src/test/java/com/networknt/schema/TypeFactoryTest.java
Instead of doing string comparison, use new jackson method to determine if a number is an integral.
The `javaSemantics` config option was added in PR #343 which partially addressed issue #334. In the notes for this PR:
> Once jackson-databind 2.12.0 is out, I'll replace my solution with a call to canConvertToExactIntegral
jackson-databind has been updated to 2.12.1 so this is available but the change has not yet been made.
PR #450 which addressed #446 missed this location which is used when calling `JsonSchemaFactory.getSchema`.
Issue #344 requested coercion of various types but the only type implemented in PR #379 was lossless narrowing, set with configuration option `losslessNarrowing`. I believe that setting is unnecessary now as this implementation of `javaSemantics` addresses the …
> Improve type validation of integrals

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchema.java
As is, this PR already resolves the first test case in [`V201909JsonSchemaTest.testAnchorValidator()`](https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/V201909JsonSchemaTest.java#L162), but not the latter two which include absolute URIs.
It causes `java.io.FileNotFoundException: http://localhost:1234/bar` due to `"$ref": "http://localhost:1234/bar#foo"` [pointing to a local `$id`](https://github.com/networknt/json-schema-validator/blob/master/src/test/resources/draft2019-09/anchor.json#L35).
I suspect this fails for the same reason some of the other V2019_09 currently fail, e.g. [`testRefValidator()`](https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/V201909JsonSchemaTest.java#L309).
It seems …
> Support fragment references using `$anchor`

- src/main/java/com/networknt/schema/DateTimeValidator.java
- src/test/resources/draft2019-09/optional/format/date-time.json
- src/test/resources/draft4/optional/format.json
- src/test/resources/draft7/optional/format/date-time.json
Fixes issue #508 by tightening up the validation regex.
> Make date-time validation align with RFC3339 (#508)

- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
- src/test/java/com/networknt/schema/CustomUriTest.java
@rongyj I have added additional logic to ensure that no null pointer exception will be thrown. However, if parentSchema or parentSchema.getParentSchema is null, the return value will be false which I don't feel comfortable with. I am wondering if you could take a look at the logic and approve the change if you are comfortable. Thanks. 
@chrswk Thanks a lot for your test case. Please review and approve the change. Now the test case is passed after checking the null. If you have other test cases, please add them to ensure the code logic is correct and nothing else is broken.
> fixes #509 NPE with oneOf and custom URI Fetcher or Factory

- doc/validators.md
I noticed a typo in the validators documentation so I wanted to help out and fix it.
> Fixed a typo in the validators documentation

- src/main/java/com/networknt/schema/AbstractJsonValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/ValidationMessage.java
- src/test/java/com/networknt/schema/Issue550Test.java
- src/test/resources/data/issue500_1.json
- src/test/resources/data/issue500_2.json
- src/test/resources/schema/issue500_1-v7.json
- src/test/resources/schema/issue500_2-v7.json
https://github.com/networknt/json-schema-validator/issues/550
> Add schemaPath to ValidationMessage.

- pom.xml
- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
when nullable = true , handlenullableFields = true and value supplied = null , then getting this failure message `"null found, string expected"` for this example:
```
"schema": {
"properties": {
"values": {
"type": "string",
"nullable": true,
"default": null
}
}
}
```
Data to be created:
```
"data": {
"values": null
}
```
Reason appears this unnecessary check for `state.isComplexValidator()` which is true only in case of oneOf . so it suppresses all handleNullableFields configurations causing the above error message.
This is related to my latest query on this issue https://github.com/networknt/json-schema-validator/issues/183
> removed unnecessary check which causes nullable=true, handleNullableFields= true with value=null to fail in all cases except OneOf

- src/main/java/com/networknt/schema/uri/URLFactory.java
Hi,
this PR improves the performance of `URLFactory.create()`. An isolated microbenchmark shows the following results.
```
Benchmark                      Mode  Cnt     Score     Error  Units
MyBenchmark.testURINew         avgt   10   717,888 ± 107,067  ns/op
MyBenchmark.testURIOld         avgt   10  1139,942 ±  13,933  ns/op
```
Cheers,
Christoph
> Improve performance of URLFactory.create()

- pom.xml
Hi,
due to the provided German localization in this lib, tests fail for maintainers with German setups.
This PR sets `-Duser.language=en -Duser.region=GB` when running tests via surefire and makes contributing a bit more convenient.
Cheers,
Christoph
> Fix broken tests on non-english setup

- pom.xml
Old version Javadoc need the JAVA_HOME environment variable, but 3.4.0 don't need it anymore.
> Upgrade javadoc plugin

- pom.xml
- src/main/java/com/networknt/schema/AnyOfValidator.java
As stated in https://github.com/networknt/json-schema-validator/issues/535, the same issue with receiving superfluous validation messages of type "required" after at least one subschema has validated without error does also apply to AnyOfValidator.
Here's my proposed fix for this second part... 😄 
@RenegadeWizard and @stevehu : please validate - many thanks! 👍
> proposal for issue #535, part 2: fix the same issue in AnyOfValidator, too

- pom.xml
- src/test/java/com/networknt/schema/Issue575Test.java
- src/test/resources/schema/issue575-2019-09.json
This pull request upgrades com.ethlo.time:itu from version 1.5.1 to version 1.7.0. Some valid negative time zone offsets (e.g. -2:30, Newfoundland time) are marked as invalid by version 1.5.1 of the itu library.
Unit tests are included to ensure that time zone offsets validate as expected and invalid time representations are marked as such.
> fixes #575

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/SpecVersion.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/main/java/com/networknt/schema/Version202012.java
- src/main/resources/jsv-messages.properties
- src/test/java/com/networknt/schema/V202012JsonSchemaTest.java
- src/test/resources/draft2020-12/items.json
- src/test/resources/draft2020-12/prefixItems.json
- src/test/resources/draft2020-12/refRemote.json
- src/test/resources/draft2020-12/uniqueItems.json
2020-12 really is not that different from 2019-09.  This set of changes allows basic validation for 2020-12 (in fact, it even borrows most of the 2019-09 unit tests).
> Add support for draft 2020-12 (#380)

- pom.xml
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/ValidationMessage.java
- src/main/java/com/networknt/schema/utils/StringUtils.java
- src/test/java/com/networknt/schema/BaseSuiteJsonSchemaTest.java
This pull request remove the commons lang dependency such that it maybe excluded in maven or gradle.
There is very little usage of Commons Lang 3 in this library and most of the usage is builtin future JDK versions (e.g. `String.isBlank` is in JDK 11).
I have left the dependency in Maven for projects that accidentally depend on this project to pull Commons Lang in as a transitive dependency.
We need this for our code base as we do not allow commons lang 3 in most of our projects.
> Remove commons lang as a compile time dependency

- doc/specversion.md
- pom.xml
This pull request updates the documentation (specversion.md) and pom.xml to reflect the V2020-12 JSON schema specifications.
> Update the specversion.md and pom.xml

- pom.xml
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/test/java/com/networknt/schema/Issue619Test.java
- src/test/resources/schema/issue619.json
> Add support for subschema references in getSchema(URI)

- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
@stevehu this is in continuation to PR #626. It is correcting the JSON path to include the exact child node index. Can you please review, approve and merge the changes.
> schema path fixes in oneOf,allOf and anyOf validators

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationMessage.java
- src/test/java/com/networknt/schema/OverwritingCustomMessageBugTest.java
- src/test/resources/data/OverwritingCustomMessageBug.json
- src/test/resources/schema/OverwritingCustomMessageBug.json
The essence of the problem seems to be that keywords are unique and can only have one custom message. When there are multiple custom messages assigned to the same keyword in a schema the mutation of the custom message can result in the incorrect error messages to be output. 
This bug goes back to, at least, version 1.0.64.
> Quick fix for wrong custom message bug

- README.md
More details and explanations: https://stackoverflow.com/questions/15171049/gradle-single-vs-double-quotes
> Improve example of Gradle dependency in README

- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/test/java/com/networknt/schema/SpecVersionDetectorTest.java
There could be cases when schemas are managed by third-parties, in this case client side logic can either use spec version defined in schema if available or some default one. Having current implementation of `SpecVersionDetector` it's not really convenient to catch exception to fallback to some default value then. Also exceptions are quite heavy mechanism, thus new method is proposed which returns an empty `Optional` value, if the schema tag is not present.
Also small refactoring of `SpecVersionDetector` class is done in order to make it true-utility class:
- class is marked as `final`
- private constructor is added
> Add ability to detect spec version optionally

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/DateTimeValidator.java
- src/main/java/com/networknt/schema/FormatValidator.java
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/PatternValidator.java
Explanation of changes: https://www.slf4j.org/faq.html#logging_performance
> Improve logging performance

- pom.xml
- src/main/java/com/networknt/schema/TypeFactory.java
- src/test/java/com/networknt/schema/Issue650Test.java
- src/test/resources/draft7/issue650.json
..to support using Java models with type byte[].
close #650
> Map BinaryNodes to type string

- README.md
Much like in https://github.com/networknt/json-schema-validator/pull/594 apache commons is banned in a code base I work in. I assumed this library was not suitable for use based on the README but after searching the issues I found the aforementioned pull request. 
Personally I believe it  should be fine to just remove it from `pom.xml` and update the README.md accordingly; as it has been several months since that change was merged, but acknowledge it may break _some_ users functionality if they are not careful about accidental transitive dependency use.
> Clarify usage of Apache commons lang in README.md

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/test/java/com/networknt/schema/Issue669Test.java
- src/test/resources/draft7/issue669.json
Resolves #669. Note that the regex has changed from what was originally agreed upon in #669. This is in order to reuse most of the test suite that was developed for #575.
> Support time offsets in `format: time`

- doc/schema-map.md
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/uri/URITranslator.java
- src/test/java/com/networknt/schema/UriMappingTest.java
issue #677 
Adds URITranslator as a FunctionalInterface
Adds MappingURITranslator to handle compatibility with specifying a Map
Adds CompositeURITranslator to handle combining the values specified in SchemaValidatorsConfig with those specified in JsonSchemaFactory.
> Adds support for translating one URI into another

- .github/workflows/ci.yml
>  [CI] Bump used latest non-LTS Java: `19` -> `20`

- doc/config.md
- doc/yaml-line-numbers.md
- src/main/java/com/networknt/schema/AbstractJsonValidator.java
- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonValidator.java
- src/main/java/com/networknt/schema/NonValidationKeyword.java
- src/main/java/com/networknt/schema/PathType.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/UnEvaluatedPropertiesValidator.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
- src/test/java/com/networknt/schema/CustomMetaSchemaTest.java
- src/test/java/com/networknt/schema/Issue687Test.java
- src/test/java/com/networknt/schema/JsonWalkTest.java
- src/test/resources/schema/issue687.json
Implemented the feature proposed in #687. Note that this update would also resolve issue #567.
Note that while doing this update I took the liberty of making a small cleanup linked to the (barely) used `AbstractJsonValidator` class. This is used in only one place really (apart from unit tests), specifically for the (non) validation of keywords.
> #687 Support for (valid) JSONPath and JSONPointer expressions as message paths

- src/main/java/com/networknt/schema/ExclusiveMaximumValidator.java
- src/main/java/com/networknt/schema/ExclusiveMinimumValidator.java
- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/java/com/networknt/schema/TypeValidatorTest.java
While investigating the issue, I found a previous refactoring left behind a large quantity of duplicated code. This has been removed.
> Corrects treating 1.0 as an integer

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/PathType.java
- src/main/java/com/networknt/schema/UnEvaluatedPropertiesValidator.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/suite/tests/draft2019-09/unevaluatedProperties.json
- src/test/suite/tests/draft2020-12/unevaluatedProperties.json
> Adds support for unevaluatedProperties that uses a non-boolean schema.

- pom.xml
Resolves #727
Added moditect plugin in a profile guarded by a JDK activation because the plugin requires JDK9+
Tests on CI run on JDK8 and thus would cause a failure.
**NOTE:** This means releases must be performed with DJK9+
There was a previous configuration for the moditect plugin using en explicit module. I left in place in case you'd rather twek it instead of having the plugin create the module from scratch:
```
$ jarviz bytecode show --file target/json-schema-validator-1.0.80.jar 
subject: json-schema-validator-1.0.80.jar
Unversioned classes. Bytecode version: 52 (Java 8) total: 145
Versioned classes 9. Bytecode version: 53 (Java 9) total: 1
$ jarviz module descriptor --file target/json-schema-validator-1.0.80.jar 
subject: json-schema-validator-1.0.80.jar
name: com.networknt.schema …
```
> Adds explicit Java module descriptor

- src/main/java/com/networknt/schema/uri/URITranslator.java
- src/main/resources/draft-04/schema
- src/main/resources/draft-06/schema
- src/main/resources/draft-07/schema
- src/main/resources/draft/2019-09/meta/applicator
- src/main/resources/draft/2019-09/meta/content
- src/main/resources/draft/2019-09/meta/core
- src/main/resources/draft/2019-09/meta/format
- src/main/resources/draft/2019-09/meta/meta-data
- src/main/resources/draft/2019-09/meta/validation
- src/main/resources/draft/2019-09/schema
- src/main/resources/draft/2020-12/meta/applicator
- src/main/resources/draft/2020-12/meta/content
- src/main/resources/draft/2020-12/meta/core
- src/main/resources/draft/2020-12/meta/format-annotation
- src/main/resources/draft/2020-12/meta/meta-data
- src/main/resources/draft/2020-12/meta/unevaluated
- src/main/resources/draft/2020-12/meta/validation
- src/main/resources/draft/2020-12/schema
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/CyclicDependencyTest.java
- src/test/java/com/networknt/schema/Issue285Test.java
- src/test/java/com/networknt/schema/Issue461Test.java
- src/test/resources/draft4/issue258/Element.json
- src/test/resources/draft4/issue258/Extension.json
- src/test/resources/draft4/issue258/Master.json
> Removes need for network access when executing unit-tests

- doc/multiple-language.md
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/CustomErrorMessageType.java
- src/main/java/com/networknt/schema/ErrorMessageType.java
- src/main/java/com/networknt/schema/I18nSupport.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/ValidationMessage.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/CustomMetaSchemaTest.java
- src/test/java/com/networknt/schema/Issue686Test.java
- src/test/resources/issue686/translations.properties
- src/test/resources/issue686/translations_de.properties
- src/test/resources/issue686/translations_fr.properties
> #686 Better localisation support

- src/main/java/com/networknt/schema/PathType.java
- src/test/java/com/networknt/schema/Issue687Test.java
- src/test/java/com/networknt/schema/PathTypeTest.java
> Resolves incomplete validation of unevaluatedProperties.

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/format/AbstractRFC3986Format.java
- src/main/java/com/networknt/schema/format/IriFormat.java
- src/main/java/com/networknt/schema/format/IriReferenceFormat.java
- src/main/java/com/networknt/schema/format/RegexFormat.java
- src/main/java/com/networknt/schema/format/TimeFormat.java
- src/main/java/com/networknt/schema/format/UriReferenceFormat.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/suite/tests/draft2019-09/optional/format/iri.json
- src/test/suite/tests/draft2020-12/optional/format/iri.json
- src/test/suite/tests/draft7/optional/format/iri.json
> Adds support for validating an IRI

- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Adds support for handling integer overflow

- doc/compatibility.md
- src/main/java/com/networknt/schema/regex/JDKRegularExpression.java
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/TestSpec.java
- src/test/resources/draft2020-12/issue495.json
- src/test/resources/draft2020-12/issue782.json
> Resolves improper anchoring of patternProperties

- src/main/java/com/networknt/schema/ItemsValidator202012.java
- src/main/java/com/networknt/schema/UnevaluatedPropertiesValidator.java
Resolves #785 
Fixing ItemsValidator202012 walk flow.
Making UnevaluatedProperties CollectorContext's key public as was in 1.0.76.
> Allow walking of schema for items keyword when non-array node is provided

- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/suite/tests/draft2019-09/ref.json
- src/test/suite/tests/draft2020-12/ref.json
- src/test/suite/tests/draft4/ref.json
- src/test/suite/tests/draft6/ref.json
- src/test/suite/tests/draft7/ref.json
> Ignores siblings of $ref when dialect is Draft 4, 6 or 7

- src/main/java/com/networknt/schema/regex/JDKRegularExpression.java
- src/test/java/com/networknt/schema/regex/Issue814Test.java
Resolves #814
@stevehu I think we should release 1.0.84 when you are ready.
> Corrects Java's failure to match an end anchor when using find()

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/test/java/com/networknt/schema/Issue832Test.java
- src/test/java/com/networknt/schema/UnknownMetaSchemaTest.java
- src/test/resources/data/issue832.json
- src/test/resources/schema/issue832-v7.json
Fixes #832 
Previously, when writing to the JsonSchemaFactory.jsonMetaSchemas hash map, the uri key was not normalized, but upon reading from the hash map, the key was normalized.
In addition, if a key is not found in this hash map, the standard meta schema for the uri is loaded.
The result was that an attempt to augment a standard meta schema with custom formatters did not work because the standard meta schema was always used instead of the custom augmented meta schema.
This change normalizes the uri keys of JsonSchemaFactory.jsonMetaSchemas on both read and write. Normalizing the uri keys on both reads and writes also eliminates the need for the forceHttps and removeEmptyFragmentSuffix arguments to the normalizeMetaSchemaUri() method.
> Normalize uri keys of JsonSchemaFactory.jsonMetaSchemas on read and write

- doc/compatibility.md
- src/main/java/com/networknt/schema/CollectorContext.java
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/RecursiveRefValidator.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/main/java/com/networknt/schema/Version201909.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/suite/tests/draft2019-09/recursiveRef.json
> Adds support for $recursiveAnchor and $recursiveRef

- pom.xml
Namespace URI can't be changed deliberately from http to https, doing so makes the XML validation to fail
https://maven.apache.org/pom.html 
https://www.w3.org/TR/xmlschema-1/
> Use correct namespace URI to pass XML validation

- pom.xml
This reverts commit 01a7da249bb3e348565410e99c269006dfdec433.
Fixes #861
> Revert "Bump io.undertow:undertow-core from 2.2.25.Final to 2.3.5.Final (#858)"

- README.md
Since its the only entry, the file https://github.com/networknt/json-schema-validator/blob/master/NOTICE could probably also be deleted.
> docs: clarify commons-lang3 exclusion only required for 1.0.81 and older

- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/ExclusiveMinimumValidator.java
- src/main/java/com/networknt/schema/NotValidator.java
getLogger parameter should match class name, where the logger is declared.
> Fix invalid class passed to getLogger

- src/main/java/com/networknt/org/apache/commons/validator/routines/InetAddressValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/main/java/com/networknt/schema/ValidationMessageHandler.java
- src/main/java/com/networknt/schema/format/DurationFormat.java
- src/main/java/com/networknt/schema/format/TimeFormat.java
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/NotAllowedValidatorTest.java
- src/test/java/com/networknt/schema/PrefixItemsValidatorTest.java
- src/test/java/com/networknt/schema/RecursiveReferenceValidatorExceptionTest.java
- src/test/resources/data/notAllowedValidation/notAllowedJson.json
- src/test/resources/schema/notAllowedValidation/notAllowedJson.json
- src/test/suite/tests/prefixItemsException/prefixItemsException.json
- src/test/suite/tests/recursiveRefException/invalidRecursiveReference.json
I have added 3 test cases.
1. Not allowed validator test case : There were no test cases covering this validation, so I have added that for test quality improvement.
2. Invalid keyword in recursive reference validator: Exception case for recursive reference validator was not handled, so I created that.
3. Empty array exception in prefixItems validator: There was no test case checking what happens if empty array is passed into prefixItems configuration, so I added that.
> Added test cases for not allowed validator, Handled invalid keyword test case for recurisve reference and empty array case for prefixItems validator

- doc/collector-context.md
After https://github.com/networknt/json-schema-validator/pull/812 some adaptions are required to retrieve data from a collector context. See also discussion in https://github.com/networknt/json-schema-validator/issues/849
> Adapt collector context documentation

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
> fix: make JsonSchemaFactory more thread-safe #891

- src/main/java/com/networknt/schema/regex/JDKRegularExpression.java
- src/main/java/com/networknt/schema/regex/JoniRegularExpression.java
- src/test/java/com/networknt/schema/regex/Issue814Test.java
- src/test/resources/draft2020-12/issue495.json
- src/test/resources/draft2020-12/issue782.json
Summary of changes:
- Fix the test resources introduced by #783 by moving the `regex` fields, such that the test framework does not skip them with a "Not a valid test case" message.
- Revert the changes introduced by #815, as those are simply incorrect.
- Extend the test coverage introduced by #815 by (a) updating the test regexes to match their intended semantics and (b) include a few negative test cases.
- Partially revert the change introduced by #783: the use of `Matcher#find()` is correct, but the `hasStartAnchor` and `hasEndAnchor` logic introduces more bugs than the issue it aims to solve.
- Extend the test coverage introduced by #783, by introducing regexes that are not covered by the `hasStartAnchor`/`hasEndAnchor` logic.
- Update the Joni regular expression integration such that …
> Fix JDK regex support

- README.md
#901  Starting with Gradle 7.x, the “compile” configuration is no longer used directly
> compile configuration is depricated

- pom.xml
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/uri/URLFactory.java
- src/main/java/com/networknt/schema/uri/URLFetcher.java
- src/main/java/com/networknt/schema/uri/URNURIFactory.java
- src/test/java/com/networknt/schema/Issue665Test.java
- src/test/resources/draft7/urn/issue665.json
- src/test/resources/draft7/urn/issue665_external_urn_ref.json
- src/test/resources/draft7/urn/issue665_external_urn_subschema.json
(Hopefully) a fix for #665.
Added a special handling for "urn:" URIs
When an the same URN is present in some id/anchor, a reference is created. Otherwise, it falls back to the current logic and a special `URIFetcher` needs to be present.
> 665: Can't load JSON schemas with URN value in id field

- doc/collector-context.md
Updates the documentation to reflect that the `CollectorContext` is no longer stored in a `ThreadLocal` and that the `CollectorContext` needs to be explicitly reused to collect across multiple runs.
> Update documentation on CollectorContext

- src/test/java/com/networknt/schema/UriMappingTest.java
Improve test coverage for com.networknt.schema.uri.URLFactory
> Basic test on URI create to improve coverage

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/test/java/com/networknt/schema/Issue928Test.java
- src/test/resources/schema/issue928-v07.json
- src/test/resources/schema/issue928-v2019-09.json
- src/test/resources/schema/issue928-v2020-12.json
https://github.com/networknt/json-schema-validator/issues/928
this makes `JsonSchemaFactory.getSchema("...#anchor")` work.
> [Issue 928]: Fix getSchema() anchor fragment lookup.

- src/main/java/com/networknt/schema/MultipleOfValidator.java
- src/test/java/com/networknt/schema/MultipleOfValidatorTest.java
Closes #917, closes #893
This adds support for type loose configuration for the `multipleOf` validator.
> Support type loose for multipleOf validator

- doc/config.md
- src/test/java/com/networknt/schema/StringCheckerTest.java
- src/test/java/com/networknt/schema/TypeValidatorTest.java
Closes #415
Add test for type validator type loose behavior for arrays and update documentation accordingly that type loose will interpret an item as an array of size 1 and that it will then only validate that that item matches the type defined for the array.
Not sure if there is supposed to be a spec which defines what type loose behavior is supposed to be.
> Add test for type loose for array and update doc for behavior

- src/test/java/com/networknt/schema/LocaleTest.java
> Locale.ENGLISH should set

- src/main/java/com/networknt/schema/AbsoluteIri.java
- src/test/java/com/networknt/schema/RefValidatorTest.java
> Fix resolve

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/main/java/com/networknt/schema/Version202012.java
- src/main/java/com/networknt/schema/Vocabularies.java
- src/main/java/com/networknt/schema/Vocabulary.java
- src/test/java/com/networknt/schema/VocabularyTest.java
Closes #753
This improves the support for the `$vocabulary` keyword used in a meta schema.
> Improve vocabulary support

- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/test/java/com/networknt/schema/PatternPropertiesValidatorTest.java
Fixes an issue with `patternProperties` setting `null` as the annotation value.
> Fix patternProperties annotation

- src/test/java/com/networknt/schema/MetaSchemaValidationTest.java
- src/test/resources/oas/v31/dialect/base
- src/test/resources/oas/v31/meta/base
- src/test/resources/oas/v31/schema-base/2022-10-07
- src/test/resources/oas/v31/schema/2022-10-07
- src/test/resources/schema/oas/v31/petstore.json
Closes #673 
This adds a tests to check that verifying an OpenAPI 3.1 schema works.
> Add test for OpenAPI 3.1 schema validation

- doc/schema-retrieval.md
- doc/upgrading.md
> Improve schema retrieval docs

- doc/upgrading.md
Closes #960 
Missed out this particular change.
This was partially done to distinguish the fail fast result from true exceptions such as when references could not be resolved.
> Update upgrading doc on fail fast

- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/result/JsonNodeResults.java
- src/test/java/com/networknt/schema/UnevaluatedPropertiesValidatorTest.java
- src/test/resources/schema/unevaluatedTests/unevaluated-tests.json
> Fix `unevaluatedProperties`

- README.md
- src/main/java/com/networknt/schema/format/DateTimeFormat.java
- src/main/java/com/networknt/schema/utils/Classes.java
Closes #973
This makes the ethlo dependency excludable. This isn't the same as making it optional as optional dependencies need to be explicitly added, while excludable needs to be explicitly excluded.
> Make ethlo excludable

- src/main/java/com/networknt/schema/MessageSourceValidationMessage.java
- src/test/java/com/networknt/schema/MessageTest.java
This fixes the use of `message` in a validator. Currently this always gets overridden.
> Fix message

- src/main/java/com/networknt/schema/format/IriFormat.java
- src/main/java/com/networknt/schema/format/IriReferenceFormat.java
- src/main/java/com/networknt/schema/format/UriFormat.java
- src/main/java/com/networknt/schema/format/UriReferenceFormat.java
- src/main/java/com/networknt/schema/resource/UriSchemaLoader.java
- src/main/java/com/networknt/schema/utils/AbsoluteIris.java
- src/test/java/com/networknt/schema/format/IriFormatTest.java
- src/test/java/com/networknt/schema/format/IriReferenceFormatTest.java
- src/test/java/com/networknt/schema/format/UriFormatTest.java
- src/test/java/com/networknt/schema/format/UriReferenceFormatTest.java
- src/test/java/com/networknt/schema/resource/UriSchemaLoaderTest.java
- src/test/java/com/networknt/schema/utils/AbsoluteIrisTest.java
Closes #981 
* The `uri` and `uri-reference` formats now reject non ASCII strings and does not allow `[` or `]` in query strings
* The `iri` and `iri-reference` formats now does not allow `[` or `]` in query strings
* The `UriSchemaLoader` now ensures proper conversion from IRI to URI eg. converting internationalized domain names or url encoding query parameters
> Fixes uri, uri-reference, iri, iri-reference formats and does iri to uri conversion

- doc/upgrading.md
- doc/walkers.md
- src/main/java/com/networknt/schema/ConstValidator.java
- src/main/java/com/networknt/schema/DynamicRefValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/ItemsValidator202012.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/MaxPropertiesValidator.java
- src/main/java/com/networknt/schema/MinPropertiesValidator.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/RecursiveRefValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/main/java/com/networknt/schema/UniqueItemsValidator.java
- src/main/java/com/networknt/schema/utils/JsonNodes.java
- src/main/java/com/networknt/schema/utils/JsonSchemaRefs.java
- src/main/java/com/networknt/schema/walk/AbstractWalkListenerRunner.java
- src/main/java/com/networknt/schema/walk/DefaultItemWalkListenerRunner.java
- src/main/java/com/networknt/schema/walk/DefaultKeywordWalkListenerRunner.java
- src/main/java/com/networknt/schema/walk/DefaultPropertyWalkListenerRunner.java
- src/main/java/com/networknt/schema/walk/WalkEvent.java
- src/main/java/com/networknt/schema/walk/WalkListenerRunner.java
- src/test/java/com/networknt/schema/Issue451Test.java
- src/test/java/com/networknt/schema/Issue467Test.java
- src/test/java/com/networknt/schema/Issue724Test.java
- src/test/java/com/networknt/schema/JsonWalkTest.java
- src/test/java/com/networknt/schema/walk/JsonSchemaWalkListenerTest.java
Closes #441, closes #467, closes #841, closes #868, closes #882
This contains breaking changes to those using the walk functionality
When using the walker with defaults the `default` across a `$ref` are properly resolved and used.
The behavior for the property listener is now more consistent whether or not validation is enabled. Previously if validation is enabled but the property is `null` the property listener is not called while if validation is not enabled it will be called. Now the property listener will be called in both scenarios.
The following are the breaking changes to those using the walk functionality. Previously there wasn't a way to get the `JsonSchema` of the schema that was referenced by the `schemaNode` and it was unclear what the `schemaLocation` or `evaluationPath` was …
> Refactor walk

- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/DiscriminatorContext.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/java/com/networknt/schema/DiscriminatorValidatorTest.java
Closes #985 
This makes changes such that a missing discriminator property is treated as if the discriminator is ignored.
This does not generate an assertion due to the missing discriminator property to be consistent with 
- #436
> Explicitly handle if the discriminator property value is null

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/DynamicRefValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/ItemsValidator202012.java
- src/main/java/com/networknt/schema/JsonValidator.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/RecursiveRefValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/test/java/com/networknt/schema/ItemsValidator202012Test.java
- src/test/java/com/networknt/schema/ItemsValidatorTest.java
- src/test/java/com/networknt/schema/PrefixItemsValidatorTest.java
- src/test/java/com/networknt/schema/TypeValidatorTest.java
- src/test/java/com/networknt/schema/walk/JsonSchemaWalkListenerTest.java
Closes #989
This changes the behavior of the walk for the item walk listener to walk the schema instead of walking the instance data. All the relevant item schemas will be called at least once with `null` as the instance node (This is not the same as `NullNode` which is a node with a value of null while `null` is the absence of the node) when there is no applicable instance data.
This also fixes the incorrect `schemaLocation` and `evaluationPath` used for the tuple schemas for `prefixItems`.
> Walk items schema instead of walking instance data

- src/main/java/com/networknt/schema/AbsoluteIri.java
- src/main/java/com/networknt/schema/OutputFormat.java
- src/test/java/com/networknt/schema/AbsoluteIriTest.java
- src/test/java/com/networknt/schema/RefValidatorTest.java
- src/test/resources/schema/common/child.json
- src/test/resources/schema/common/child2.json
- src/test/resources/schema/main/main.json
Fixes the IRI resolve at the root when there is no starting slash.
For instance given `classpath:resource.json` and resolving `test.json` will now return `classpath:test.json`.
> Fix root classpath resolve

- src/main/java/com/networknt/schema/IfValidator.java
- src/test/java/com/networknt/schema/IfValidatorTest.java
Closes #1009
Previously with the validate schema option enabled, the walk would delegate to validate. But calling validate on the schemas will not walk the schema.
> Fix walk for if validator with validation

- doc/compatibility.md
In compatibility.md, in the Keywords Support table, changed "defs" to "$defs"
> Changed defs to $defs in compatibility.md

- doc/validators.md
**PR Summary**:
In PR #697, the `src/test/resources/draft7/if-then-else.json` was moved to `src/test/suite/tests/draft7/if-then-else.json`. This PR adjusts the docs accordingly.
> Fix the broken link to `if-then-else.json`

- pom.xml
- src/test/java/com/networknt/schema/MaximumValidatorTest.java
- src/test/java/com/networknt/schema/MinimumValidatorTest.java
This updates the versions used by the dependencies to a recent version.
As Jackson has fixed the `Incorrect deserialization for BigDecimal numbers` issue since 2.16.0 the `MaximumValidatorTest` and `MinimumValidatorTest` needed to be updated with the new expectation that the bug no longer applies
> Update dependency versions

- src/main/java/com/networknt/schema/OutputFormat.java
- src/main/java/com/networknt/schema/output/HierarchicalOutputUnitFormatter.java
- src/main/java/com/networknt/schema/output/ListOutputUnitFormatter.java
- src/main/java/com/networknt/schema/output/OutputUnitData.java
- src/test/java/com/networknt/schema/OutputUnitTest.java
Closes #1030
This adds a constructor argument for `OutputFormat.Hierarchical` and `OutputFormat.List` to add a function to allow mapping of the `ValidationMessage` to an `Object`. This allows the message to be customized or allows the `ValidationMessage` to be passed through as is if the identity function is used.
> Allow customization of assertion for outputunit

- src/main/java/com/networknt/schema/SchemaLocation.java
- src/main/java/com/networknt/schema/utils/JsonNodes.java
- src/test/java/com/networknt/schema/SchemaLocationTest.java
- src/test/resources/schema/example-escaped.yaml
Closes #1037, closes #1036
Performs the unescaping for JSON Pointer in `SchemaLocation.Fragment`.
> Fix schema location for escaped json pointer

- README.md
- doc/compatibility.md
Updates the JSON Schema badges from [bowtie](https://bowtie.report/#/implementations/java-networknt-json-schema-validator) as the URL has moved.
> Update JSON Schema badges

- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/java/com/networknt/schema/AllOfValidatorTest.java
- src/test/java/com/networknt/schema/AnyOfValidatorTest.java
- src/test/java/com/networknt/schema/OneOfValidatorTest.java
Closes #1034
Validate `allOf`, `oneOf` and `anyOf` contains array
> Validate allOf, oneOf and anyOf contains array

- README.md
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonNodeLocation.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAware.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareArrayNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareBigIntegerNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareBinaryNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareBooleanNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareDecimalNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareDoubleNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareFloatNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareIntNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareLongNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareNullNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareObjectNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwarePOJONode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareShortNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonLocationAwareTextNode.java
- src/main/java/com/networknt/schema/serialization/node/JsonNodeFactoryFactory.java
- src/main/java/com/networknt/schema/serialization/node/LocationJsonNodeFactory.java
- src/main/java/com/networknt/schema/serialization/node/LocationJsonNodeFactoryFactory.java
- src/main/java/com/networknt/schema/utils/JsonNodes.java
- src/test/java/com/networknt/schema/JsonSchemaFactoryTest.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/java/com/networknt/schema/utils/JsonNodesTest.java
This allows easier tracking of the json node location information such as the line and column number by providing a default implementation that can be configured.
This is not configured by default as it will adversely affect performance.
> Allow tracking of json node location information

- src/main/java/com/networknt/schema/JsonType.java
- src/main/java/com/networknt/schema/TypeFactory.java
- src/test/java/com/networknt/schema/TypeFactoryTest.java
Optimized the performance of the `type` validator by refactoring `getValueNodeType`.
> Optimize getValueNodeType

- src/main/java/com/networknt/schema/format/IriFormat.java
- src/main/java/com/networknt/schema/format/IriReferenceFormat.java
- src/test/java/com/networknt/schema/format/IriFormatTest.java
- src/test/java/com/networknt/schema/format/IriReferenceFormatTest.java
> Fix for incorrect validation failure for %-encoded '[' and ']' characters

- src/main/java/com/networknt/schema/format/RegexFormat.java
- src/main/java/com/networknt/schema/regex/JDKRegularExpression.java
- src/main/java/com/networknt/schema/regex/JoniRegularExpression.java
- src/main/java/com/networknt/schema/regex/RegularExpression.java
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/regex/JoniRegularExpressionTest.java
- src/test/suite/tests/draft-next/optional/ecmascript-regex.json
- src/test/suite/tests/draft2020-12/optional/ecmascript-regex.json
This fixes the test failure from the JSON Schema Test Suite in `optional/ecmascript-regex.json` as `joni` does not detect invalid escapes.
This makes the following changes
* The `regex` format has been changed to also follow the configuration of whether to use `ecma-262` compliant regex. Previously it always used the `jdk` regex.
* The `JoniRegularExpression` implementation uses a regex to detect if an invalid escape is used as `joni` doesn't detect invalid escapes. In actuality it's upstream `Oniguruma` doesn't actually support ecma as a syntax.
* The latest tests from the JSON Schema Test Suite for `optional/ecmascript-regex.json` has been updated. In actuality it doesn't change anything but it is clearer that `"format": "regex"` is used in the test
* The test harness now enables format …
> Detect invalid escape for ecmascript

- src/main/java/com/networknt/schema/CachedSupplier.java
- src/test/java/com/networknt/schema/CachedSupplierTest.java
Change to allow the delegate to be garbage collected.
> Release delegate held by cached supplier

- src/main/java/com/networknt/schema/ConstValidator.java
- src/test/java/com/networknt/schema/ConstValidatorTest.java
- src/test/resources/const-messages-override.properties
Closes #846 
This makes it possible for a custom locale properties file to generate the desired message for the `const` validator.
This doesn't make it the default as doing so will make it inconsistent with the rest of the messages for other validators.
The input node value that caused the failure can be consistently retrieved using `message.getInstanceNode()` and its path from `message.getInstanceLocation()` and a custom `OutputFormat` implementation can be used to consistently format the messages.
> Allow customization of const message to include input value

- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
Deprecate config for `unevaluatedItems` and `unevaluatedProperties` as this is no longer needed and doesn't do anything since the validators were rewritten to use annotations as it doesn't cost additional performance by collecting annotations if not needed and will always collect annotations for the relevant validators if needed.
> Deprecate config for unevaluatedItems and unevaluatedProperties

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/NotAllowedValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/RequiredValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
Sets the initial size of the `ArrayList` to the expected size when known.
> Set initial array list size

- README.md
- doc/compatibility.md
- doc/ecma-262.md
- src/main/java/com/networknt/schema/regex/JDKRegularExpression.java
- src/test/java/com/networknt/schema/regex/GraalJSRegularExpressionTest.java
- src/test/java/com/networknt/schema/regex/JDKRegularExpressionTest.java
- src/test/java/com/networknt/schema/regex/JoniRegularExpressionTest.java
Improves the documentation on regular expressions and adds additional tests.
Disabled tests for the current issue for not properly matching anchors when there are newlines have been added for the JDK and Joni implementations. The tests show that GraalJS works. Tests also added that ensures that there is no implicit anchoring is used.
> Improve documentation on regular expressions

- src/main/java/com/networknt/schema/format/AbstractRFC3986Format.java
- src/test/java/com/networknt/schema/format/IriFormatTest.java
- src/test/java/com/networknt/schema/format/IriReferenceFormatTest.java
- src/test/java/com/networknt/schema/format/UriFormatTest.java
- src/test/java/com/networknt/schema/format/UriReferenceFormatTest.java
Closes #1070 
This fixes `iri`, `iri-reference`, `uri` and `uri-reference` formats to allow inputs conforming to RFC 3986 / RFC 3987 for which `URI` will throw a syntax error as it implements RFC 2396.
In particular inputs like `http://`, `//` and `about:` are now accepted.
A more complete and proper fix will likely require an additional library like Apache Jena IRI but will defer this until it is really needed.
> Fix iri, iri-reference, uri and uri-reference

- src/main/java/com/networknt/schema/SchemaLocation.java
- src/test/java/com/networknt/schema/SchemaLocationTest.java
This fixes the case where the schema location has a `#` in the fragment for example `https://example.com/example.yaml#/paths/~1subscribe/post/callbacks/myEvent/{request.body#~1callbackUrl}/post/requestBody/content/application~1json/schema`.
> Fix schema location with hash in fragment

- src/main/java/com/networknt/schema/utils/JsonNodes.java
- src/test/java/com/networknt/schema/oas/OpenApi30Test.java
> Fix json pointer with number in fragment

- src/main/java/com/networknt/schema/OneOfValidator.java
- src/test/java/com/networknt/schema/OneOfValidatorTest.java
Fixes issue when oneOf when discriminator enabled but no discriminator causes no details in errors. Such cases should behave as a normal oneOf.
> Fix oneOf when discriminator enabled but no discriminator

- README.md
- src/main/java/com/networknt/schema/AbsoluteIri.java
- src/main/java/com/networknt/schema/regex/AllowRegularExpressionFactory.java
- src/main/java/com/networknt/schema/resource/AllowSchemaLoader.java
- src/main/java/com/networknt/schema/resource/ClasspathSchemaLoader.java
- src/main/java/com/networknt/schema/resource/DisallowSchemaLoader.java
- src/test/java/com/networknt/schema/regex/AllowRegularExpressionFactoryTest.java
- src/test/java/com/networknt/schema/resource/AllowSchemaLoaderTest.java
- src/test/java/com/networknt/schema/resource/DisallowSchemaLoaderTest.java
Add some details on security considerations and mitigations and some implementations.
> Add security considerations and mitigations

- src/main/java/com/networknt/schema/JsonSchema.java
- src/test/java/com/networknt/schema/oas/OpenApi30Test.java
Fix evaluationPath and schemaLocation in getSubSchema when having a number in fragment due to `SchemaLocation.of` parsing.
> Fix evaluationPath and schemaLocation in getSubSchema

- doc/quickstart.md
- src/main/java/com/networknt/schema/ValidationMessageHandler.java
- src/test/java/com/networknt/schema/SampleTest.java
This removes the alternate custom error message mechanism. This mechanism isn't really documented and cannot be disabled.
> Remove alternate custom error message mechanism

- src/main/java/com/networknt/schema/UnevaluatedItemsValidator.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
- src/test/java/com/networknt/schema/VocabularyTest.java
Fixes the activeDialect for custom meta schema to return the specification instead of attempting to determine from the iri.
> Fix activeDialect for custom meta schema

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonNodePath.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/SchemaLocation.java
- src/test/java/com/networknt/schema/SchemaLocationTest.java
Closes #1082 
Adds some possible performance improvements and fixes an issue with resolve
> Improve performance and fixes

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/test/java/com/networknt/schema/Issue1091Test.java
- src/test/resources/data/issue1091.json
- src/test/resources/schema/issue1091.json
Closes #1091 
This optimizes the `hasAdjacentKeywordInEvaluationPath` function by attempting to detect when the `instanceLocation` changes as it is really trying to find the adjacent keywords to the instance location for use later during annotation processing.
> Optimize hasAdjacentKeywordInEvaluationPath

- src/main/java/com/networknt/schema/EnumValidator.java
- src/test/java/com/networknt/schema/EnumValidatorTest.java
- src/test/java/com/networknt/schema/Issue342Test.java
- src/test/java/com/networknt/schema/Issue662Test.java
- src/test/java/com/networknt/schema/Issue898Test.java
- src/test/java/com/networknt/schema/OutputFormatTest.java
Closes #1094 
This fixes the enum validator messages as previously object and array nodes were empty strings and the text nodes outputted text without the quotes.
For example given the schema
```json
{
"enum": [6, "foo", [], true, {"foo": 12}]
}
```
The message is now
`: does not have a value in the enumeration [6, "foo", [], true, {"foo":12}]`
> Fix enum validator messages for object, array and text nodes

- src/main/java/com/networknt/schema/oas/OpenApi30.java
- src/test/java/com/networknt/schema/oas/OpenApi30Test.java
> Fix exclusiveMinimum and exclusiveMaximum for OpenAPI 3.0

- doc/upgrading.md
- src/main/java/com/networknt/schema/ValidationMessage.java
- src/main/java/com/networknt/schema/output/OutputUnit.java
- src/test/java/com/networknt/schema/OutputUnitTest.java
Only corrected an URL, to a file which was moved in 2023.
> Correct URL to jsonschema-validation-output-machines.md documentation

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/test/java/com/networknt/schema/UnevaluatedPropertiesValidatorTest.java
Closes #1123
This fixes the incorrect logic for determining if there is a change in the instance location.
> Fix hasAdjacentKeywordInEvaluationPath optimisation

- src/main/java/com/networknt/schema/Version4.java
- src/test/java/com/networknt/schema/ExclusiveMinimumValidatorTest.java
> Remove warning for exclusiveMinimum and exclusiveMaximum for Draft 4

- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
- src/test/java/com/networknt/schema/TypeValidatorTest.java
> Fix nullable issue

- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/test/java/com/networknt/schema/ValidationMessageHandlerTest.java
> Fix custom error message for union type

- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/main/java/com/networknt/schema/format/BaseFormatJsonValidator.java
- src/test/java/com/networknt/schema/FormatValidatorTest.java
Closes #1144
This also fixes the `SchemaValidatorsConfig` builder to initialise `formatAssertionsEnabled` to `null` instead of `false`.
> Fix explicit disabling of format assertions

- src/main/java/com/networknt/schema/AbsoluteIri.java
- src/test/java/com/networknt/schema/AbsoluteIriTest.java
Closes #1146
Fix the issue where a relative iri with a colon is treated as an absolute iri.
> Fix relative iris with colons

- src/main/java/com/networknt/schema/TypeFactory.java
- src/test/java/com/networknt/schema/JsonWalkTest.java
Closes #1151 
Fixes the NPE by having `TypeFactory.getValueNodeType((JsonNode node, SchemaValidatorsConfig config)` handle the case where a `null` was passed in as the node.
I had considered if it should be ensured that the node inputs should always be non null and always replace `null` by `MissingNode` instead. For instance having `PropertiesValidator` set the input as `MissingNode` instead of `null`. But since `JsonNode.get(String fieldName)` returns `null` for missing nodes I wasn't sure it would be appropriate.
> Fix NPE when walking a missing node that will have missing properties

- src/test/java/com/networknt/schema/OverrideValidatorTest.java
Closes #1158
Fixes the test that wasn't setting format assertions to be enabled.
> Fix OverrideValidatorTest

- src/main/java/com/networknt/schema/RequiredValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/java/com/networknt/schema/RequiredValidatorTest.java
Closes #1185 
Add support for ignoring readOnly or writeOnly fields for required validation.
> Support readOnly and writeOnly for required validation

- src/main/java/com/networknt/schema/format/TimeFormat.java
- src/test/java/com/networknt/schema/format/TimeFormatTest.java
Closes #1187
Fixes the time format validation and adds the appropriate unit tests.
> Fix time format validation

- pom.xml
- src/main/java/com/networknt/schema/regex/JoniRegularExpression.java
- src/test/java/com/networknt/schema/regex/JoniRegularExpressionTest.java
Closes #1192 
This fixes the underlying discrepancies in the code ranges for the character classes `\d`, `\D`, `\w`, `\W`, `\s`, `\S` in ECMA-262 vs the mappings to the unicode general categories. As such this also fixes the case where these character classes are used in a character set.
In the process of fixing this it was also noted that `\p{digit}` is mapping to `\d` where it should be to `\p{Nd}` so this was fixed as well.
> Fix JoniRegularExpression compatibility issues with ECMA-262
