- pom.xml
Reverts networknt/json-schema-validator#16
> Revert "Switch to targeting Java 7"

- src/main/java/com/networknt/schema/ValidationMessage.java
Make getArguments public and setArguments package-private.
> Change access modifiers in ValidationMessage

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
This change makes fields final and changes `allowedProperties` to a `HashSet` so lookups are in O(1) time.
> Optimize AdditionalPropertiesValidator

- src/main/java/com/networknt/schema/ValidatorTypeCode.java
79acd4d0 removed the fromValue method from ValidatorTypeCode. Restore it to its state before 79acd4d0.
> Restore validator type code from value

- CHANGELOG.md
- pom.xml
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationContext.java
see for details:
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-8088
> Remove unused dependency to slf4j-ext due to security issue

- src/main/java/com/networknt/schema/TypeValidator.java
https://github.com/networknt/light-rest-4j/issues/50
> Adding support for nullable fields

- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
> Fixing min/max int validation to not output decimal constraints.

- README.md
> fixes issue #120

- src/main/java/com/networknt/schema/MaximumValidator.java
- src/main/java/com/networknt/schema/MinimumValidator.java
related issue: https://github.com/networknt/json-schema-validator/issues/147
> Fix min/max validator

- src/main/java/com/networknt/schema/DateTimeValidator.java
- src/main/java/com/networknt/schema/FormatKeyword.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/test/resources/tests/optional/format.json
Related issue: https://github.com/networknt/json-schema-validator/issues/138
> Added DateTimeValidator

- src/main/java/com/networknt/schema/FormatKeyword.java
- src/main/java/com/networknt/schema/UUIDValidator.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/test/java/com/networknt/schema/JsonSchemaTest.java
- src/test/resources/tests/uuid.json
add new format validator for uuid:
format: uuid
> fixes issue #151

- src/main/java/com/networknt/schema/DateTimeValidator.java
- src/test/resources/tests/optional/format.json
Related issue: https://github.com/networknt/json-schema-validator/issues/155
Changed the time pattern from 12-hour pattern to 24-hour pattern
> Fix 24-hour validation error

- src/main/java/com/networknt/schema/ValidatorTypeCode.java
> replace reflection in ValidatorTypeCode

- doc/yaml.md
Added an example code snippet for yaml validation
> Added an example code snippet for yaml validation

- doc/schema-map.md
@rhwood With a recent issue about the meta schema URL switching from HTTP to HTTPS, I have received so many requests from users on how to use the URL mapping. I have drafted a document without a lot of details in a branch and wondering if you could review and add more details about the usage. Thanks a lot for the good work and it is a very important feature of the library now.
> fixes #222 add document for URL mapping

- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/ValidatorTypeCode.java
- src/test/java/com/networknt/schema/V201909JsonSchemaTest.java
- src/test/java/com/networknt/schema/V6JsonSchemaTest.java
- src/test/java/com/networknt/schema/V7JsonSchemaTest.java
I have implemented the ContainsValidator, I based it mostly on the ItemsValidator.
I noticed we already had tests for this, so I simply uncommented these.
Based on the tests, if the validation is attached to something not an array, we simply skip the validation, I guess this is fine?
> Issue-226 ContainsValidator

- README.md
- doc/collector_context.md
- src/main/java/com/networknt/schema/Collector.java
- src/main/java/com/networknt/schema/CollectorContext.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ThreadInfo.java
- src/main/java/com/networknt/schema/ValidationResult.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
These changes are with respect to issue #249 . Please let me know your comments.
> Changes for adding collector context

- pom.xml
- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/java/com/networknt/schema/V4JsonSchemaTest.java
- src/test/java/com/networknt/schema/V6JsonSchemaTest.java
- src/test/java/com/networknt/schema/V7JsonSchemaTest.java
- src/test/resources/draft4/idRef.json
- src/test/resources/draft6/idRef.json
- src/test/resources/draft7/idRef.json
Fix for 'Dereferencing subschemas by $id with $ref in the same file does not seem to work' - issue https://github.com/networknt/json-schema-validator/issues/255
> 255 issue id ref

- pom.xml
- src/main/java/com/networknt/schema/PatternValidator.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/java/com/networknt/schema/PatternPropertiesValidatorTest.java
Add ECMA-262 regex check support for `pattern`.
Fixes #15
> Use ECMA-262 validator when requested

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/main/java/com/networknt/schema/urn/URNFactory.java
- src/test/java/com/networknt/schema/UrnTest.java
- src/test/resources/draft7/urn/account.schema.json
- src/test/resources/draft7/urn/test.json
- src/test/resources/draft7/urn/urn.schema.json
Check before UrnTest test. 
In the test I pass a inputStream to getSchema this means that URIFactory can't determine the relative path. I add the URNFactory for manage that.
> added test schema

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/DependenciesValidator.java
- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/test/java/com/networknt/schema/CyclicDependencyTest.java
- src/test/resources/draft4/cyclic/Element.json
- src/test/resources/draft4/cyclic/Extension.json
- src/test/resources/draft4/cyclic/Master.json
@stevehu @mihaiba Thi is my solution for resolved the cyclic dependencies 
- Now the JsonSchema class have a initialize method that load the validators from the schima.
- In the JsonSchemaFactory in the method getSchema from URI I managed a cache. In this case the jsonSchema.initialize is put after the store in the cache for avoid loop. 
Please @mihaiba could you check if your case is covered with my solution?
Regards
Francesco
> #258 fixed cyclic dependencies

- README.md
- doc/config.md
- corrected url to test case that demonstrates usage of failfast
> Trivial readme fixes

- src/main/java/com/networknt/schema/PatternValidator.java
> Add null check in validationContext.getConfig()

- src/main/java/com/networknt/schema/CollectorContext.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
I have a use case where I need to get all the keys that were added to CollectorContext and operate on the values together for all these keys. Added a getAll method which gives me all the data collected by CollectorContext object. Please review.
> Adding getAll method on CollectorContext class.

- doc/validators.md
Add document for custom validators, for issue #32
> Support Custom Validators

- doc/compatibility.md
Fixes #288  .
Adds compatibility matrix for validation keywords and formats.
> Compatibility matrix

- src/main/java/com/networknt/schema/ContainsValidator.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
- src/test/java/com/networknt/schema/UnknownMetaSchemaTest.java
> (#317) Compatible with Jackson 2.9.x

- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/test/java/com/networknt/schema/Issue285Test.java
Fix compatible issue with Jackson 2.9.x introduced by 3a3e1a8 d5a861a
> Follow up(#317) Compatible with Jackson 2.9.x

- src/test/resources/draft7/if-then-else.json
#357 example from https://json-schema.org/understanding-json-schema/reference/conditionals.html
> IF-THEN-ELSE Conditional with properties attribute

- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/test/resources/draft2019-09/propertyNames.json
- src/test/resources/draft6/propertyNames.json
- src/test/resources/draft7/propertyNames.json
> #326 property names with pattern

- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/test/java/com/networknt/schema/Issue375Test.java
- src/test/resources/data/issue375.json
- src/test/resources/draft2019-09/issue375.json
> PropertyNames to return validator value on error (#375)

- doc/quickstart.md
- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/DependenciesValidator.java
- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonValidator.java
- src/main/java/com/networknt/schema/NonValidationKeyword.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PatternValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/test/java/com/networknt/schema/CollectorContextTest.java
- src/test/java/com/networknt/schema/CustomMetaSchemaTest.java
- src/test/java/com/networknt/schema/Issue406Test.java
- src/test/java/com/networknt/schema/JsonWalkTest.java
Hi @stevehu,
to fix #406, here's my proposal. I've also done a few code clean-ups, especially when member `JsonSchema` instances were not final. Please refer to `Issue406Test` for the behaviour of the change.
Florian
> Added JsonValidator#preloadJsonSchema()

- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/test/resources/openapi3/discriminator.json
> Implementation of #436

- src/test/java/com/networknt/schema/AdditionalPropertiesOneOfFailsTest.java
- src/test/resources/data/AdditionalPropertiesOneOfFailsTest.json
- src/test/resources/openapi3/AdditionalPropertiesOneOfFailsTest.json
Hi Steve,
This test is more complex than others I've seen, hopefully the scope is not too wide now.
Greetz, and thanks, Huub
> AdditionalPropertiesOneOfFails test

- src/main/java/com/networknt/schema/JsonSchema.java
Fixes https://github.com/networknt/json-schema-validator/issues/538
> Allow fetching /properties from map with comparator

- src/main/java/com/networknt/schema/utils/JsonNodeUtil.java
Hi,
this PR is loosely related to #564 and removes one easy case of the relatively expensive `CollectorContext` infrastructure.
Cheers,
Christoph
> Remove unused variable in JsonNodeUtil

- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/test/resources/schema/unevaluatedTests/unevaluated-tests.json
Here is a fix proposition for issue: https://github.com/networknt/json-schema-validator/issues/582
Kind regards,
Kevan.
> Fix unevaluatedPropeties with patternProperties and type union (#582)

- src/main/java/com/networknt/schema/Version201909.java
- src/main/java/com/networknt/schema/Version202012.java
Partial fix for for https://github.com/networknt/json-schema-validator/issues/79
> Add NonValidationKeyword "else" on 201909 and 202012

- src/main/java/com/networknt/schema/FormatKeyword.java
- src/main/java/com/networknt/schema/format/DurationValidator.java
- src/test/java/com/networknt/schema/DurationFormatValidatorTest.java
Add  validatior for duration format introduced on the Draft 2019-09 : https://json-schema.org/draft/2019-09/release-notes.html
> add validator for duration format

- src/test/java/com/networknt/schema/SpecVersionDetectorTest.java
- src/test/java/com/networknt/schema/SpecVersionTest.java
- src/test/resources/draft2020-12/schemaTag.json
This pull request updates the spec version tests to reflect the V2020-12 JSON schema specifications.
> Update spec version tests

- src/main/java/com/networknt/schema/JsonSchema.java
Added a new walk method that allows walking from a specific schema node.
> adding new walk method to start walking from a specific part of a given schema node

- src/main/java/com/networknt/schema/DateTimeValidator.java
Does a few things:
- Stops the error-level log: this is unusual for a validation library - the schema validation errors already tell us that something is wrong (albeit with slightly less precision, that's why the log remains, but at lower level). 
- Stops throwing exceptions. Throwing exceptions is unusual in this library: it seems more validators avoid this at all costs (makes sense - it's extremely expensive).
- Validate formatName in the constructors to avoid simple mistakes (and detect invalid formatName earlier than validation time).
- Gets rid of the Runnable that was only serving as a wrapper for `try-catch`, which isn't really needed here.
> Avoid throwing exceptions and error-level logging

- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/suite/remotes/draft-next/id/my_identifier.json
- src/test/suite/remotes/draft-next/unknownKeyword/my_identifier.json
- src/test/suite/remotes/draft2019-09/id/my_identifier.json
- src/test/suite/remotes/draft2019-09/unknownKeyword/my_identifier.json
- src/test/suite/remotes/draft2020-12/id/my_identifier.json
- src/test/suite/remotes/draft2020-12/unknownKeyword/my_identifier.json
- src/test/suite/remotes/id/my_identifier.json
- src/test/suite/remotes/unknownKeyword/my_identifier.json
- src/test/suite/tests/draft-next/id.json
- src/test/suite/tests/draft-next/unknownKeyword.json
- src/test/suite/tests/draft2019-09/id.json
- src/test/suite/tests/draft2019-09/unknownKeyword.json
- src/test/suite/tests/draft2020-12/id.json
- src/test/suite/tests/draft2020-12/unknownKeyword.json
- src/test/suite/tests/draft4/id.json
- src/test/suite/tests/draft6/id.json
- src/test/suite/tests/draft6/unknownKeyword.json
- src/test/suite/tests/draft7/id.json
- src/test/suite/tests/draft7/unknownKeyword.json
> Corrects malformed tests

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/CollectorContext.java
- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/TypeValidator.java
- src/main/java/com/networknt/schema/UnEvaluatedPropertiesValidator.java
- src/test/resources/schema/unevaluatedTests/unevaluated-tests.json
> Adds explicit support for tracking evaluated properties

- src/main/java/com/networknt/schema/PathType.java
- src/test/java/com/networknt/schema/Issue687Test.java
> #750 Escape double-quote in produced JSON Path expressions

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Adds support for validating uri-template formats

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Enables validation of json-pointer formats

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Supports relative-json-pointer validation.

- src/main/java/com/networknt/schema/JsonMetaSchema.java
- src/main/java/com/networknt/schema/format/AbstractFormat.java
- src/main/java/com/networknt/schema/format/AbstractRFC3339Format.java
- src/main/java/com/networknt/schema/format/PatternFormat.java
- src/main/java/com/networknt/schema/format/UriFormat.java
- src/main/java/com/networknt/schema/format/UriReferenceFormat.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/java/com/networknt/schema/OverrideValidatorTest.java
**_NOTE: This change depends on #762 being merged._**
Resolves #763
> Supports uri-reference format.

- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/SpecVersion.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Adds support for cross-draft validation

- src/main/java/com/networknt/schema/AdditionalPropertiesValidator.java
- src/main/java/com/networknt/schema/AllOfValidator.java
- src/main/java/com/networknt/schema/AnyOfValidator.java
- src/main/java/com/networknt/schema/BaseJsonValidator.java
- src/main/java/com/networknt/schema/ContainsValidator.java
- src/main/java/com/networknt/schema/DependenciesValidator.java
- src/main/java/com/networknt/schema/DependentSchemas.java
- src/main/java/com/networknt/schema/IfValidator.java
- src/main/java/com/networknt/schema/ItemsValidator.java
- src/main/java/com/networknt/schema/ItemsValidator202012.java
- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/JsonSchemaFactory.java
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/OneOfValidator.java
- src/main/java/com/networknt/schema/PatternPropertiesValidator.java
- src/main/java/com/networknt/schema/PrefixItemsValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/main/java/com/networknt/schema/PropertyNamesValidator.java
- src/main/java/com/networknt/schema/RefValidator.java
- src/main/java/com/networknt/schema/SpecVersion.java
- src/main/java/com/networknt/schema/SpecVersionDetector.java
- src/main/java/com/networknt/schema/UnevaluatedItemsValidator.java
- src/main/java/com/networknt/schema/UnevaluatedPropertiesValidator.java
- src/main/java/com/networknt/schema/UnionTypeValidator.java
- src/main/java/com/networknt/schema/ValidationContext.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
> Makes JsonSchemaFactory solely responsible for creating JsonSchema instances.

- src/main/java/com/networknt/schema/FormatKeyword.java
- src/test/java/com/networknt/schema/Issue784Test.java
- src/test/resources/issue784/schema.json
> Allows to override date-time and duration validators

- src/main/java/com/networknt/schema/PatternValidator.java
- src/test/java/com/networknt/schema/Issue792.java
> Supports fail-fast when a pattern does not match.

- src/main/java/com/networknt/schema/JsonSchema.java
- src/main/java/com/networknt/schema/SchemaValidatorsConfig.java
- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/CustomMessageTest.java
- src/test/java/com/networknt/schema/TestSpec.java
- src/test/resources/schema/customMessageTests/custom-message-disabled-tests.json
> Support config param to disable custom messages from schema

- src/test/java/com/networknt/schema/AbstractJsonSchemaTestSuite.java
- src/test/java/com/networknt/schema/JsonSchemaTestSuiteTest.java
- src/test/java/com/networknt/schema/suite/TestCase.java
- src/test/java/com/networknt/schema/suite/TestSource.java
- src/test/java/com/networknt/schema/suite/TestSpec.java
- src/test/suite/tests/draft2019-09/unevaluatedProperties.json
- src/test/suite/tests/draft2020-12/format.json
- src/test/suite/tests/draft2020-12/unevaluatedProperties.json
> Corrects issue with deserializing JSON Schema Test Suite tests.

- src/main/java/com/networknt/schema/DependentSchemas.java
- src/test/java/com/networknt/schema/Issue724Test.java
> Adds support for walking dependentSchemas

- src/main/java/com/networknt/schema/IfValidator.java
> Adds support for walking if-then-else

- src/main/java/com/networknt/schema/BaseJsonValidator.java
See [Applicators](https://json-schema.org/draft/2020-12/json-schema-core.html#name-applicators)
Resolves #209
> Ignores fail-fast when evaluating a member of an applicator

- src/main/java/com/networknt/schema/NotValidator.java
> Corrects walk behavior in NotValidator

- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/test/java/com/networknt/schema/Issue604Test.java
> Corrects source of NPE

- src/test/resources/draft7/issue590.json
It appears that this was fixed somewhere along the way as I cannot reproduce the issue with the provided example. I'm adding the unit-test to ensure we don't regress.
Resolves #590
> Adds a unit-test for #590 even though this issue appears to be fixed.

- pom.xml
- src/main/java/com/networknt/schema/NotValidator.java
- src/main/java/com/networknt/schema/PropertiesValidator.java
- src/test/java/com/networknt/schema/Issue604Test.java
- src/test/resources/draft7/issue590.json
> Reverts Undertow version to 2.2.25.Final

- pom.xml
> Downgrade logback to 1.3.14 for JDK 8 compatibility

- pom.xml
There has been numerous improvements to both the performance,  test coverage and bug-fixes.
> Upgrade ITU library to version 1.8

- src/test/java/com/networknt/schema/UnevaluatedPropertiesValidatorTest.java
Closes #967 
This adds a test case to verify that the issue raised has already been fixed.
> Add unevaluatedProperties test

- src/main/java/com/networknt/schema/PatternValidator.java
- src/test/java/com/networknt/schema/PatternValidatorTest.java
Closes #1105 
Fix PatternValidator to not log for fail fast
> Fix PatternValidator to not log for fail fast

- pom.xml
> Bump io.undertow:undertow-core from 2.2.33.Final to 2.2.35.Final

- pom.xml
Hope you like this one too 👍🏻 @stevehu
> Upgrade many libraries
